version: 2.1

jobs:
  build:
    working_directory: ~/firecalc

    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      - run:
          name: Run tests
          command: mvn clean test

      - run:
          name: Generate test report
          command: mvn surefire-report:report-only

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
            ls -la ~/firecalc/target
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn package