version: 2.1

jobs:
  build:
    working_directory: ~/firecalc

    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      - run: ls -la

      - run: pwd

      - run: mvn clean test

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn clean package